project:
  type: website
  render:
    - "*.qmd"
    - "weeks/"
    - "core/notebooks/"
    - "core/ipynb/"
    - "!core/labs/"
    - "!core/slides/"
    - "!core/labs-solutions/"
    - "!core/projects/"
    - "!core/technos/"
  output-dir: _site

website:
  page-navigation: true
  title: "IFEBY310 - Spring 2025"
  description: "Homepage for course IFEBY310 - Big Data Technologies, Master MIDS Spring 2025."
  site-url: "https://s-v-b.github.io/IFEBY310/"

  repo-url: https://github.com/s-v-b/IFEBY310
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with blood, sweat, tears, and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Stéphane Boucheron"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/UniversiteParisCite_logo_horizontal_couleur_RVB.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/s-v-b/IFEBY310
        text: "GitHub organization"
      - icon: person-fill
        text: "Moodle"
        menu:
          - text: Discussion forum
            url: https://moodle.u-paris.fr/course/view.php?id=28534
          - text: Dépot 
            url: https://moodle.u-paris.fr/course/view.php?id=28534
          - text: Notes
            url: https://moodle.u-paris.fr/course/view.php?id=28534

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Information"
        contents:
          - href: index.qmd
            text: Glimpse
          - href: cours-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Team
      - section: "Support"
        contents:
          - href: computing-access.qmd
            text: "Computing resources"
          - href: computing-virtualenv.qmd
            text: "Virtual environments"
          - href: computing-jupyter.qmd
            text: "Jupyter"
          - href: quarto-format.qmd
            text: "Quarto"
          - href: computing-docker.qmd
            text: "Docker"
      - href: slides-listings.qmd
        text: Slides
      - href: notebooks-listings.qmd
        text: Notebooks
      - href: projects-listings.qmd
        text: Homeworks
      - href: weeks-listings.qmd
        text: Journal

resources:
  - "/projectsls _s/hmw-table-wrangling.html"  
  - "/data/drug-enforcement.json.zip"
  - "/data/webdata.parquet.zip"    

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true

execute:
  freeze: auto
  cache: true

editor: source
lang: en-US

